[tool.poetry]
name = "sprachhilfer"
version = "0.1.0"
description = "An LLM based German writing tcorrection for the learners of the language"
authors = ["Shawon Ashraf"]
license = "MIT"
readme = "README.md"

package-mode = false

[tool.poetry.dependencies]
python = ">=3.12"


[tool.poetry.group.dev.dependencies]
ruff = "^0.9.4"
pre-commit = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
